### ISSUE TITLE
The config variable only accepts my first group name

### ISSUE THREAD

**Issue by AdeTheux** [hubot-scripts/hubot-group-alias#7]
I'm passing this command as I'd like to create 2 groups:
heroku config:add HUBOT_GROUP_ALIAS=SC=Arnaud,An,Bj,Lu;CSx=P,M

Name are being shortened on purpose. But the config only stores the first group, never anything after the " ; ".
So if I read the config I only have HUBOT_GROUP_ALIAS=SC=Arnaud,An,Bj,Lu

Am I doing something wrong?
Thanks

**Comment by cycomachead** [comment]
Hmm, what you have defined looks good. Have you checked the logs to see if there's any error output?

**Comment by cycomachead** [comment]
Actually, wait, I sense a different problem. Can you do `heroku config:get HUBOT_GROUP_ALIAS`

I suspect that that `;` was treated as a separate command in the shell. If you surround your alias in quotes everything should be OK:
`heroku config:add HUBOT_GROUP_ALIAS='SC=Arnaud,An,Bj,Lu;CSx=P,M'`

If that fails, could you see if the Heroku web UI reports the same values for the variable as you set it to?

**Comment by AdeTheux** [comment]
Thanks, it works well with quotes.

**Comment by cycomachead** [comment]
No problem!
